# Test code
sonar.tests=tests/

# Exclude tests from source analysis and ignore exploratory assignments
sonar.exclusions=\
  tests/**,\
  src/adhoc/**/*

# Supported Python version
sonar.python.version=3.12
